name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      run: npm ci
    - name: Publish
      run: |
        npm run build
        cd dist
        npm publish --tag next --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: Successfully published `@skyux-sdk/e2e@${{ steps.vars.outputs.tag }}` to NPM. http://github.com/${{ github.repository }}/blob/${{ steps.vars.outputs.tag }}/CHANGELOG.md
